; G-Code Motion System
; Generated by G-Code Generator
; Print Dimensions: 220.0mm x 220.0mm x 220.0mm
; Cycles: 500
; Feed Rate: 100.0 mm/min
; 
G90 ; Absolute positioning
G21 ; Metric units
G28 ; Home all axes
F100.0 ; Set feed rate

G0 X10.0 Y10.0 Z5.0 ; Move to start position

; === CYCLE 1 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 2 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 3 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 4 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 5 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 6 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 7 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 8 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 9 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 10 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 11 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 12 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 13 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 14 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 15 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 16 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 17 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 18 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 19 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 20 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 21 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 22 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 23 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 24 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 25 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 26 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 27 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 28 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 29 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 30 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 31 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 32 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 33 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 34 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 35 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 36 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 37 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 38 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 39 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 40 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 41 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 42 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 43 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 44 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 45 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 46 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 47 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 48 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 49 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 50 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 51 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 52 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 53 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 54 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 55 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 56 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 57 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 58 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 59 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 60 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 61 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 62 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 63 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 64 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 65 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 66 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 67 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 68 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 69 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 70 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 71 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 72 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 73 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 74 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 75 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 76 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 77 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 78 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 79 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 80 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 81 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 82 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 83 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 84 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 85 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 86 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 87 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 88 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 89 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 90 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 91 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 92 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 93 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 94 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 95 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 96 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 97 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 98 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 99 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 100 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 101 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 102 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 103 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 104 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 105 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 106 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 107 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 108 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 109 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 110 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 111 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 112 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 113 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 114 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 115 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 116 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 117 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 118 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 119 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 120 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 121 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 122 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 123 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 124 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 125 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 126 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 127 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 128 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 129 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 130 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 131 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 132 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 133 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 134 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 135 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 136 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 137 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 138 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 139 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 140 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 141 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 142 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 143 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 144 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 145 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 146 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 147 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 148 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 149 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 150 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 151 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 152 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 153 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 154 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 155 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 156 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 157 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 158 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 159 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 160 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 161 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 162 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 163 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 164 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 165 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 166 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 167 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 168 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 169 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 170 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 171 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 172 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 173 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 174 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 175 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 176 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 177 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 178 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 179 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 180 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 181 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 182 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 183 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 184 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 185 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 186 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 187 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 188 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 189 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 190 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 191 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 192 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 193 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 194 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 195 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 196 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 197 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 198 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 199 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 200 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 201 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 202 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 203 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 204 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 205 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 206 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 207 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 208 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 209 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 210 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 211 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 212 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 213 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 214 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 215 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 216 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 217 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 218 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 219 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 220 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 221 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 222 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 223 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 224 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 225 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 226 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 227 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 228 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 229 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 230 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 231 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 232 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 233 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 234 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 235 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 236 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 237 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 238 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 239 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 240 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 241 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 242 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 243 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 244 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 245 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 246 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 247 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 248 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 249 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 250 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 251 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 252 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 253 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 254 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 255 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 256 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 257 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 258 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 259 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 260 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 261 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 262 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 263 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 264 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 265 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 266 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 267 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 268 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 269 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 270 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 271 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 272 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 273 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 274 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 275 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 276 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 277 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 278 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 279 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 280 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 281 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 282 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 283 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 284 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 285 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 286 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 287 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 288 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 289 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 290 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 291 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 292 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 293 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 294 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 295 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 296 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 297 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 298 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 299 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 300 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 301 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 302 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 303 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 304 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 305 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 306 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 307 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 308 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 309 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 310 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 311 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 312 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 313 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 314 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 315 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 316 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 317 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 318 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 319 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 320 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 321 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 322 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 323 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 324 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 325 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 326 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 327 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 328 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 329 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 330 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 331 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 332 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 333 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 334 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 335 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 336 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 337 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 338 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 339 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 340 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 341 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 342 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 343 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 344 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 345 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 346 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 347 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 348 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 349 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 350 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 351 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 352 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 353 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 354 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 355 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 356 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 357 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 358 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 359 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 360 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 361 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 362 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 363 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 364 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 365 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 366 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 367 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 368 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 369 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 370 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 371 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 372 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 373 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 374 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 375 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 376 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 377 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 378 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 379 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 380 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 381 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 382 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 383 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 384 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 385 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 386 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 387 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 388 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 389 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 390 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 391 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 392 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 393 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 394 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 395 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 396 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 397 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 398 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 399 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 400 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 401 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 402 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 403 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 404 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 405 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 406 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 407 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 408 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 409 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 410 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 411 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 412 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 413 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 414 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 415 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 416 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 417 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 418 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 419 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 420 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 421 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 422 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 423 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 424 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 425 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 426 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 427 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 428 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 429 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 430 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 431 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 432 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 433 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 434 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 435 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 436 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 437 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 438 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 439 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 440 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 441 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 442 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 443 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 444 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 445 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 446 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 447 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 448 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 449 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 450 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 451 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 452 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 453 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 454 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 455 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 456 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 457 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 458 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 459 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 460 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 461 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 462 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 463 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 464 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 465 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 466 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 467 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 468 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 469 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 470 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 471 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 472 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 473 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 474 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 475 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 476 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 477 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 478 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 479 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 480 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 481 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 482 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 483 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 484 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 485 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 486 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 487 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 488 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 489 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 490 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 491 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 492 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 493 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 494 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 495 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 496 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 497 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 498 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 499 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4
G0 Z7.0 ; Z-Hop

; === CYCLE 500 ===
G1 X230.0 Y10.0 Z5.0 ; Corner 1
G1 X230.0 Y230.0 Z5.0 ; Corner 2
G1 X10.0 Y230.0 Z5.0 ; Corner 3
G1 X10.0 Y10.0 Z5.0 ; Corner 4

G0 Z7.0 ; Raise Z
G28 ; Return home
M84 ; Disable motors

; End of G-Code